default: &default
  adapter: mysql2
  database: ceto
  username: root #Cambiar
  password: ceto #Cambiar
  host: CeTo #Cambiar
  timeout: 5000

development:
  <<: *default
  database: ceto/development

test:
  <<: *default
  database: ceto/test

production:
  <<: *default
  database: ceto/production