default: &default
  adapter: mysql2
  database: sql10175832
  username: sql10175832 #Cambiar
  password: YKNZlwj3gI #Cambiar
  host: sql10.freesqldatabase.com #Cambiar
  timeout: 5000

development:
  <<: *default
  database: sql10175832

test:
  <<: *default
  database: sql10175832

production:
  <<: *default
  database: sql10175832